### ISSUE TITLE
Basenji Small

### ISSUE THREAD

**Issue by wawpaopao** [Zehui127/1d-swin#1]
Merry Christmas! Could you please advise where I can download Basenji Small?

**Comment by Zehui127** [comment]
Hi @wawpaopao ,

Currently, you can obtain the original Basenji dataset and process it to create the 'Basenji Small' variant. This involves truncating the central section of each data point, as described in our paper. You can access the original dataset from the Google Cloud at the following link:
[Original Basenji Dataset](https://console.cloud.google.com/storage/browser/basenji_barnyard/data)

**Comment by wawpaopao** [comment]
Thanks!
